---
services:
  docs-server:
    labels:
      log-filter: firebolt-docs-staging
    build: &build-firebolt-docs
      context: .
      args: &build-args-firebolt-docs
        host: docs-server
        port: 80
        user_id: "${USER_ID}"
        user_name: "${USER_NAME}"
        repo_url: git@github.com/firebolt-analytics/firebolt-docs-staging.git
      dockerfile: ./scripts/docker/Dockerfile
    healthcheck:
      test: "curl -f http://localhost >/dev/null || exit 1"
      interval: 15s
      retries: 40
    extra_hosts:
      - "docs-server=0.0.0.0"

  link-check:
    image: raviqqe/muffet:2.10.2
    command: ["--color=never", "--include=http://docs-server", "http://docs-server"]
    depends_on:
      docs-server:
        condition: service_healthy

  localhost-firebolt-docs:
    build:
      <<: *build-firebolt-docs
      args:
        <<: *build-args-firebolt-docs
        host: localhost
        port: 8080
    network_mode: host
