name: Deploy to GitHub Pages

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: jekyll/builder:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Jekyll
      run: |
        apt-get update 
        apt-get install -y ruby-dev
        gem install jekyll bundler --user-install
        export PATH="$HOME/.gem/ruby/$(ls /usr/lib/ruby/gems/)/bin:$PATH"

    - name: Build site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages
        destination_dir: ${{ github.ref_name }}  # Deploy to a subdirectory named after the branch

