name: Build and Deploy Preview

on:
  push:
    branches: 
      - '*'  # Trigger on all branches

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: 'build'
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref_name }}

      - name: Build the site using Docker
        run: |
          docker run --rm \
            -v $(pwd):/srv/jekyll \
            -v $(pwd)/vendor/bundle:/usr/local/bundle \
            --user $(id -u):$(id -g) \
            -e JEKYLL_ENV=production \
            -e JEKYLL_CACHE_DIR=/tmp/jekyll-cache \
            jekyll/builder:latest \
            sh -c "jekyll clean && jekyll build"
        working-directory: build  # Adjust if necessary

      - name: Deploy to GitHub Pages
        env:
          TARGET_BRANCH: gh-pages
        run: |
          # Copy the build output to a directory named after the branch
          PREVIEW_DIR="preview-${GITHUB_REF_NAME}"
          mkdir -p $PREVIEW_DIR
          cp -r _site/* $PREVIEW_DIR
          
          # Switch to the gh-pages branch
          git fetch origin gh-pages
          git checkout gh-pages
          
          # Copy the preview to the gh-pages branch under the branch-specific directory
          cp -r $PREVIEW_DIR/* .
          
          # Commit and push the changes
          git add -A
          git commit -m "Deploy preview for ${GITHUB_REF_NAME}"
          git push origin gh-pages
      
