name: Deploy to GitHub Pages

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: jekyll/builder:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set Cache Directory
      run: echo "Setting JEKYLL_CACHE_DIR to /tmp/.jekyll-cache"
      env:
        JEKYLL_CACHE_DIR: /tmp/.jekyll-cache

    - name: Install dependencies
      run: |
        cd docs  # Change to the directory containing your Gemfile
        bundle config set --local path 'vendor/bundle'
        bundle install --jobs 4 --retry 3

    - name: Build site
      run: |
        cd docs  # Change to the directory containing your Gemfile
        bundle exec jekyll build --trace

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_site
        publish_branch: gh-pages
