name: Push to remote repositories

on:
  push:
    branches: 
      - '*'  # Trigger on all branches

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: 'build'
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref_name }}

      - name: Generate app token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_CI_GITOPS_APP_ID }}
          private_key: ${{ secrets.GH_APP_CI_GITOPS_KEY_PEM }}

      - name: Checkout Guru Synch Target
        run: actions/checkout@v4

      - name: Checkout Preview Target
        run: actions/checkout@v4
        with:

      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions

      - name: Push Guru
        env: 
          TARGET_BRANCH: "main"
        run: |
          cp -r build/* deploysync
          cd deploysync
          git add -A
          git commit -m "feat(no_issue): update with $GITHUB_SHA"
          git push origin $TARGET_BRANCH || echo "remote repository already synced"

      - name: Push Preview
        env: 
          TARGET_BRANCH: ${{ github.ref_name }}  # Use the branch name that triggered the workflow
        run: |
          cp -r build/* preview
          cd preview
          git add -A
          git commit -m "feat(no_issue): update with $GITHUB_SHA"
          git push origin $TARGET_BRANCH || echo "remote repository already synced"

