name: Production Build and Deploy
on:
  push:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Node.js
        uses: actions/setup-node@v2

      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: 'build'

      - name: Build
        run: |
          cd build
          git checkout gh-pages
          git pull https://github.com/firebolt-db/firebolt-db.github.io.git gh-pages
          git push origin


      - name: Checkout Staging Target
        uses: actions/checkout@v2
        with:
          repository: firebolt-analytics/firebolt-docs-staging
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: 'deploy'
      
      - name: Push files to target
        run: |
          cp -r build/* deploy
          cd deploy
          git add .
          git commit -m $GITHUB_SHA
          git push

      - name: Checkout Guru Synch Target
        uses: actions/checkout@v2
        with:
          repository: firebolt-analytics/firebolt-doc-to-guru
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: 'deploysync'

      - name: Push files to target
        run: |
          cp -r build/* deploysync
          cd deploysync
          git add .
          git commit -m $GITHUB_SHA
          git push
