# Custom action that deploys a page to GitHub pages.
# https://docs.github.com/en/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages
# https://github.com/rossjrw/pr-preview-action

name: Deploy Docs PR Preview

on:
  pull_request:
    branches:
      - gh-pages
  workflow_dispatch:

concurrency: preview-${{ github.ref }}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site
      - name: Deploy Preview 
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./_site

